// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//Default [FirebaseOptions] for use with your Firebase apps.
///
//Example:
//```dart
//import 'firebase_options.dart';
//// ...
//await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
//);
//```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLIsnLUuXHZIItNRmlzsNF5YFneEg2pY',
    appId: '1:211574184384:web:a2fc650bc86f33ffe59025',
    messagingSenderId: '211574184384',
    projectId: 'notes-app-9690a',
    authDomain: 'notes-app-9690a.firebaseapp.com',
    storageBucket: 'notes-app-9690a.firebasestorage.app',
    measurementId: 'G-2Q14BCBR8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM13AFKxKhYR4L5sssU_gJkFIXFZuAOuI',
    appId: '1:211574184384:android:53c5ff34bd8a501ce59025',
    messagingSenderId: '211574184384',
    projectId: 'notes-app-9690a',
    storageBucket: 'notes-app-9690a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCorrh4E0Z-fDny_u1cC8O9sP-E_1_iOQE',
    appId: '1:211574184384:ios:f6762aa9ca440efee59025',
    messagingSenderId: '211574184384',
    projectId: 'notes-app-9690a',
    storageBucket: 'notes-app-9690a.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCorrh4E0Z-fDny_u1cC8O9sP-E_1_iOQE',
    appId: '1:211574184384:ios:f6762aa9ca440efee59025',
    messagingSenderId: '211574184384',
    projectId: 'notes-app-9690a',
    storageBucket: 'notes-app-9690a.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuLIsnLUuXHZIItNRmlzsNF5YFneEg2pY',
    appId: '1:211574184384:web:df991ec9af50abc8e59025',
    messagingSenderId: '211574184384',
    projectId: 'notes-app-9690a',
    authDomain: 'notes-app-9690a.firebaseapp.com',
    storageBucket: 'notes-app-9690a.firebasestorage.app',
    measurementId: 'G-74G57DCVHS',
  );
}
